name: analyst_toolkit_deploy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - jupyter
  - pandas
  - numpy
  - scipy
  - pyyaml
  - black
  - flake8
  - pytest
  - pyyaml
  - pip:
      - typer
      - rich
