# Normalization module template (minimal)
notebook: true
run_id: ""
logging: "auto"

normalization:
  run: true
  rules:
    rename_columns: {}
    standardize_text_columns: []
    value_mappings: {}
    fuzzy_matching:
      run: false
      settings: {}
    parse_datetimes: {}
    preview_columns: []
    coerce_dtypes: {}
  settings:
    show_inline: true
    export: true
    as_csv: false
    export_path: "exports/reports/normalization/normalization_report.xlsx"
    checkpoint:
      run: true
      checkpoint_path: "exports/joblib/{run_id}/{run_id}_m03_df_normalized.joblib"

