# Outlier Handling module template (minimal)
notebook: true
run_id: ""
logging: "auto"

outlier_handling:
  run: true
  input_df_path: "exports/joblib/{run_id}/{run_id}_m05_outliers_flagged.joblib"
  detection_results_path: "exports/joblib/{run_id}/{run_id}_m05_detection_results.joblib"
  handling_specs:
    __global__:
      strategy: 'none'
  settings:
    show_inline: true
    export:
      run: true
      export_path: "exports/reports/outliers/handling/outlier_handling_report.xlsx"
      as_csv: false
    checkpoint:
      run: true
      checkpoint_path: "exports/joblib/{run_id}/{run_id}_m06_df_handled.joblib"

