# Outlier Detection module template (minimal)
notebook: true
run_id: ""
logging: "auto"

outlier_detection:
  run: true
  input_path: "data/processed/df_validated.csv"
  detection_specs:
    __default__:
      method: 'iqr'
      iqr_multiplier: 2.0
  exclude_columns: []
  append_flags: true
  plotting:
    run: true
    plot_save_dir: "exports/plots/outliers/{run_id}"
    plot_types: ['box', 'hist']
    show_plots_inline: true
  export:
    run: true
    export_dir: "exports/reports/outliers/detection/"
    as_csv: false
  checkpoint:
    run: true
    checkpoint_path: "exports/joblib/{run_id}/{run_id}_m05_outliers_flagged.joblib"

