name: Release (Build-Only)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build dists
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          python -m build
          python -m twine check dist/*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.ref_name }}
          path: dist/*

  # Note: Automated publishing to TestPyPI/PyPI is intentionally disabled
  # until repository secrets are configured. When ready, re-enable publish
  # jobs using pypa/gh-action-pypi-publish with API tokens.
