name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Allows manual triggering

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build

      - name: Create GitHub Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

      - name: Upload Test Artifact (on manual run)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.ref_name }}
          path: dist/*
